### ISSUE TITLE
TypeError: Cannot read property 'event' of null(…)

### ISSUE THREAD

**Issue by ferllings** [blueberryapps/redux-file-upload#13]
Hello,

I have this error, on this line. Using the Example code.
`app.js:118136 Uncaught (in promise) TypeError: Cannot read property 'event' of null(…)`

on this line:

```
  componentDidMount() {
    FileAPI.event.on(this.refs.fileInput, 'change', this.handleFileChange);
```

**Comment by jakubkottnauer** [comment]
Hi, please let me know if version 0.0.15 fixed it for you.

**Comment by vojtatranta** [comment]
lol
