### ISSUE TITLE
Uncaught TypeError: Cannot read property 'array' of undefined

### ISSUE THREAD

**Issue by proxiex** [blueberryapps/redux-file-upload#21]
`Uncaught TypeError: Cannot read property 'array' of undefined`
I don't know if I am doing something wrong but the as soon as I import `redux-file-upload` I get the above error. 
I checked the code and it seems what is in your repo is different from what I npm install, you use PRT here but in the node_modules file, its `_react.ProptTypes.array`

**Comment by kepi74** [comment]
Thank you for your report! We will check our code and will notify you what is wrong.

**Comment by kepi74** [comment]
@proxiex You were right, there was older version of code in npm registry. Actualised version of package, 0.0.19, was released few minutes ago. Check it out, please.

**Comment by proxiex** [comment]
Thank you so much, makes my life a lot easier.
